name: py4chemoinfo
channels:
        - conda-forge
dependencies:
        - scikit-learn
        - seaborn
        - matplotlib
        - rdkit
        - pip
        - pip:
          - -r file:requirements.txt
           
